// Infrared transmitter on the Cardputer-Adv's onboard emitter (G44).
//
// The carrier is generated by the LEDC peripheral and gated on and off to form
// marks and spaces. Timing is taken from esp_timer_get_time() rather than
// delayMicroseconds(), because the latter is measured against the FreeRTOS tick
// and a 560 us NEC pulse cannot afford tick-sized error.
//
// Interrupts are NOT disabled for the frame. A NEC frame is about 67 ms and
// masking interrupts for that long would upset Wi-Fi and the watchdog. IR
// receivers tolerate roughly a quarter of a bit period of jitter, which this
// stays inside -- but it is the reason the Control surface turns Wi-Fi off
// before transmitting.

#pragma once

#include <cstdint>

#include "ir/protocol.h"

namespace orthrus::hal {

class IrTx {
public:
    bool begin();
    bool ready() const { return ready_; }

    // Sends one frame. Blocks for the length of the frame, which is tens of
    // milliseconds.
    void send(const ir::PulseTrain& train);

    // Sends a frame `repeats` times with the protocol's own inter-frame gap.
    // Many devices ignore a single frame, expecting a remote's key-held repeat.
    void sendRepeated(const ir::PulseTrain& train, ir::Protocol p,
                      uint8_t repeats);

    uint32_t framesSent() const { return framesSent_; }

    // Parks the emitter off. Leaving the carrier running would both waste power
    // and quietly interfere with every other remote in the room.
    void idle();

private:
    bool     ready_      = false;
    uint32_t framesSent_ = 0;
};

IrTx& sharedIrTx();

}  // namespace orthrus::hal
